# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Vanilla site with vanilla theme.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

githubio_https_redirect: true
google_analytics: vanilla

paginate: 10 # pagination based on number of posts

# Build settings
markdown: kramdown
